version: "3.8"
services:
  app:
    container_name: flask-app
    image: flask-app
    build: .
    networks:
      - duo-network
  nginx:
    container_name: nginx
    image: nginx:latest
    networks:
      - duo-network
    ports:
      - published: 80
        target: 80
        protocol: tcp
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - "flask-app"

networks:
  duo-network:
# volumes:
#   example-vol:
